import {Course, Job} from '../types';

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Complete React Native Development',
    description:
      'Master mobile app development with React Native. Build cross-platform apps.',
    category: 'Mobile Development',
    level: 'Intermediate',
    duration: 40,
    rating: 4.8,
    enrolled: 15420,
    skills: ['React', 'JavaScript', 'Mobile Development'],
    modules: [
      {
        id: 'm1',
        title: 'Introduction to React Native',
        duration: 3,
        completed: false,
        lessons: [
          {
            id: 'l1',
            title: 'Setting up environment',
            duration: 1,
            type: 'video',
            completed: false,
          },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'Advanced Algorithms & Data Structures',
    description:
      'Deep dive into algorithms, data structures, and problem-solving techniques.',
    category: 'Computer Science',
    level: 'Advanced',
    duration: 50,
    rating: 4.9,
    enrolled: 12340,
    skills: ['Algorithms', 'Data Structures', 'Problem Solving'],
    modules: [],
  },
  {
    id: '3',
    title: 'Full Stack Web Development Bootcamp',
    description:
      'Learn to build complete web applications from front-end to back-end.',
    category: 'Web Development',
    level: 'Beginner',
    duration: 60,
    rating: 4.7,
    enrolled: 25600,
    skills: ['Web Development', 'JavaScript', 'Node.js'],
    modules: [],
  },
  {
    id: '4',
    title: 'Machine Learning A-Z',
    description:
      'Comprehensive course covering supervised and unsupervised learning.',
    category: 'Data Science',
    level: 'Intermediate',
    duration: 45,
    rating: 4.8,
    enrolled: 18900,
    skills: ['Machine Learning', 'Python', 'Data Analysis'],
    modules: [],
  },
  {
    id: '5',
    title: 'DevOps Engineering Complete Guide',
    description:
      'Master CI/CD, containerization, and cloud deployment strategies.',
    category: 'DevOps',
    level: 'Advanced',
    duration: 35,
    rating: 4.6,
    enrolled: 9800,
    skills: ['DevOps', 'Docker', 'Kubernetes'],
    modules: [],
  },
  {
    id: '6',
    title: 'UI/UX Design Masterclass',
    description:
      'Learn to create beautiful and user-friendly interfaces.',
    category: 'Design',
    level: 'Beginner',
    duration: 30,
    rating: 4.7,
    enrolled: 14200,
    skills: ['UI Design', 'UX Research', 'Figma'],
    modules: [],
  },
  {
    id: '7',
    title: 'Cloud Architecture with AWS',
    description:
      'Design and deploy scalable cloud solutions on Amazon Web Services.',
    category: 'Cloud Computing',
    level: 'Advanced',
    duration: 42,
    rating: 4.9,
    enrolled: 11500,
    skills: ['AWS', 'Cloud Architecture', 'System Design'],
    modules: [],
  },
  {
    id: '8',
    title: 'Python for Data Science',
    description:
      'Master Python programming for data analysis and visualization.',
    category: 'Data Science',
    level: 'Beginner',
    duration: 38,
    rating: 4.8,
    enrolled: 22100,
    skills: ['Python', 'Data Analysis', 'Pandas'],
    modules: [],
  },
];

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior React Native Developer',
    company: 'TechCorp Inc.',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$120k - $160k',
    matchScore: 95,
    requiredSkills: ['React', 'JavaScript', 'Mobile Development'],
    description:
      'Looking for an experienced React Native developer to build our mobile apps.',
    postedDate: '2 days ago',
  },
  {
    id: '2',
    title: 'Full Stack Software Engineer',
    company: 'StartupXYZ',
    location: 'Remote',
    type: 'Remote',
    salary: '$100k - $140k',
    matchScore: 88,
    requiredSkills: ['JavaScript', 'Node.js', 'React'],
    description:
      'Join our growing team to build innovative web applications.',
    postedDate: '1 week ago',
  },
  {
    id: '3',
    title: 'Machine Learning Engineer',
    company: 'AI Innovations',
    location: 'New York, NY',
    type: 'Full-time',
    salary: '$130k - $180k',
    matchScore: 82,
    requiredSkills: ['Python', 'Machine Learning', 'TensorFlow'],
    description:
      'Work on cutting-edge AI projects and deploy ML models at scale.',
    postedDate: '3 days ago',
  },
  {
    id: '4',
    title: 'DevOps Engineer',
    company: 'CloudSystems',
    location: 'Austin, TX',
    type: 'Full-time',
    salary: '$110k - $150k',
    matchScore: 78,
    requiredSkills: ['Docker', 'Kubernetes', 'AWS'],
    description:
      'Manage our cloud infrastructure and improve deployment pipelines.',
    postedDate: '5 days ago',
  },
  {
    id: '5',
    title: 'UI/UX Designer',
    company: 'DesignStudio',
    location: 'Los Angeles, CA',
    type: 'Full-time',
    salary: '$90k - $120k',
    matchScore: 75,
    requiredSkills: ['Figma', 'UI Design', 'User Research'],
    description:
      'Create beautiful interfaces for web and mobile applications.',
    postedDate: '1 week ago',
  },
  {
    id: '6',
    title: 'Data Scientist',
    company: 'DataDriven Co.',
    location: 'Boston, MA',
    type: 'Full-time',
    salary: '$115k - $155k',
    matchScore: 85,
    requiredSkills: ['Python', 'Data Analysis', 'SQL'],
    description:
      'Analyze complex datasets and provide actionable insights.',
    postedDate: '4 days ago',
  },
  {
    id: '7',
    title: 'Backend Developer',
    company: 'WebServices LLC',
    location: 'Seattle, WA',
    type: 'Full-time',
    salary: '$105k - $145k',
    matchScore: 80,
    requiredSkills: ['Node.js', 'Database', 'API Development'],
    description:
      'Build scalable backend services and APIs for our platform.',
    postedDate: '1 week ago',
  },
  {
    id: '8',
    title: 'Mobile App Developer',
    company: 'AppBuilders',
    location: 'Chicago, IL',
    type: 'Contract',
    salary: '$80k - $110k',
    matchScore: 90,
    requiredSkills: ['React Native', 'iOS', 'Android'],
    description:
      '6-month contract to develop a customer-facing mobile application.',
    postedDate: '2 days ago',
  },
  {
    id: '9',
    title: 'Cloud Solutions Architect',
    company: 'Enterprise Tech',
    location: 'Denver, CO',
    type: 'Full-time',
    salary: '$140k - $190k',
    matchScore: 72,
    requiredSkills: ['AWS', 'System Design', 'Cloud Architecture'],
    description:
      'Design enterprise-level cloud solutions for our clients.',
    postedDate: '1 week ago',
  },
  {
    id: '10',
    title: 'Frontend Developer',
    company: 'WebInnovate',
    location: 'Remote',
    type: 'Remote',
    salary: '$95k - $130k',
    matchScore: 87,
    requiredSkills: ['React', 'JavaScript', 'CSS'],
    description:
      'Build responsive and performant web applications.',
    postedDate: '3 days ago',
  },
];